name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
version: VERSION
core: 8.x
configure: config.sync

# Information added by drush on 2019-03-20
version: '8.6.13'
project: 'drupal'
datestamp: 1553061679